"""IPTC form schema and XMP mappings. Lists use semicolons in the form."""
# key, label, namespace, property, container (text, Alt, Bag, Seq)
GROUPS = {
'Description': [
('alt_text','Alt text','iptc','AltTextAccessibility','Alt'),('extended_description','Extended description','iptc','ExtDescrAccessibility','Alt'),('caption_writer','Description writers','photoshop','CaptionWriter','text'),('headline','Headline','photoshop','Headline','text'),('keywords','Keywords','dc','subject','Bag'),('persons','Persons shown','ext','PersonInImage','Bag'),('org_names','Featured organization names','ext','OrganisationInImageName','Bag'),('org_codes','Featured organization codes','ext','OrganisationInImageCode','Bag'),('scene','IPTC scene','iptc','Scene','Bag')],
'Creator': [('creator','Creator / photographer','dc','creator','Seq'),('creator_identity','Creator identity','plus','ImageCreator','json'),('creator_job','Creator job title','photoshop','AuthorsPosition','text'),('copyright','Copyright','dc','rights','Alt'),('credit','Credit','photoshop','Credit','text'),('source','Source','photoshop','Source','text'),('copyright_url','Copyright URL','rights','WebStatement','text'),('usage_terms','Rights usage terms','rights','UsageTerms','Alt')],
'Event / Location': [('event','Event','ext','Event','text'),('date_created','Time and date (ISO 8601)','photoshop','DateCreated','text'),('city','City','photoshop','City','text'),('location','Location','iptc','Location','text'),('state','State / province','photoshop','State','text'),('country','Country','photoshop','Country','text'),('country_code','ISO country code','iptc','CountryCode','text'),('subject_code','IPTC subject code','iptc','SubjectCode','Bag'),('genre','Intellectual genre','iptc','IntellectualGenre','text'),('location_created','Location in which image was created','ext','LocationCreated','json'),('location_shown','Locations shown','ext','LocationShown','json')],
'Workflow': [('title','Title / object name','dc','title','Alt'),('job_id','Job ID / transmission reference','photoshop','TransmissionReference','text'),('instructions','Special instructions','photoshop','Instructions','text'),('edit_status','Edit status','photoshop','EditStatus','text'),('category','Category','photoshop','Category','text'),('supp_categories','Supplemental categories (up to 3)','photoshop','SupplementalCategories','Bag'),('urgency','Urgency','photoshop','Urgency','text')],
'Releases / Artwork': [('model_ages','Model ages','ext','ModelAge','Bag'),('model_info','Additional model information','ext','AdditionalModelInformation','text'),('age_disclosure','Model age disclosure (PLUS URI)','plus','MinorModelAgeDisclosure','text'),('model_release','Model release status (PLUS URI)','plus','ModelReleaseStatus','text'),('model_ids','Model release IDs','plus','ModelReleaseID','Bag'),('property_release','Property release status (PLUS URI)','plus','PropertyReleaseStatus','text'),('property_ids','Property release IDs','plus','PropertyReleaseID','Bag'),('artwork','Artwork or objects','ext','ArtworkOrObject','json')],
'Contact': [('contact_address','Contact address','iptc','CiAdrExtadr','contact'),('contact_city','Contact city','iptc','CiAdrCity','contact'),('contact_state','Contact state','iptc','CiAdrRegion','contact'),('contact_zip','Contact ZIP','iptc','CiAdrPcode','contact'),('contact_country','Contact country','iptc','CiAdrCtry','contact'),('contact_emails','Contact emails','iptc','CiEmailWork','contact'),('contact_phones','Contact phones','iptc','CiTelWork','contact'),('contact_urls','Contact web URLs','iptc','CiUrlWork','contact')],
'Licensing': [('image_creators','Image creators','plus','ImageCreator','json'),('copyright_owners','Copyright owners','plus','CopyrightOwner','json'),('supplier','Image supplier','plus','ImageSupplier','json'),('supplier_image_id',"Supplier's image ID",'plus','ImageSupplierImageID','text'),('registry','Image registry entries','ext','RegistryId','json'),('licensors','Licensors','plus','Licensor','json')],
'Media': [('max_width','Maximum image width','plus','MaxAvailWidth','text'),('max_height','Maximum image height','plus','MaxAvailHeight','text'),('digital_source','Digital source type (IPTC URI)','ext','DigitalSourceType','text'),('data_mining','Data mining (IPTC URI)','ext','DataMining','text'),('constraints','Other constraints','ext','OtherConstraints','text')]
}
# Creator identity and Image creators describe the same standard XMP structure.
GROUPS['Creator'] = [f for f in GROUPS['Creator'] if f[0] != 'creator_identity']
FIELDS = {f[0]: f for group in GROUPS.values() for f in group}
STRUCTURE_HINTS = {
'location_created':'Sublocation, City, ProvinceState, CountryName, CountryCode, WorldRegion, LocationId',
'location_shown':'Sublocation, City, ProvinceState, CountryName, CountryCode, WorldRegion, LocationId',
'artwork':'AOTitle, AOCreator, AODateCreated, AOSource, AOSourceInvNo, AOCopyrightNotice',
'image_creators':'ImageCreatorName, ImageCreatorID', 'copyright_owners':'CopyrightOwnerName, CopyrightOwnerID',
'supplier':'ImageSupplierName, ImageSupplierID', 'registry':'RegOrgId, RegItemId',
'licensors':'LicensorName, LicensorID, LicensorEmail, LicensorURL, LicensorTelephone1'
}
